export const searchSuggessionsArray = [
  "Margarita",
  "Martini",
  "Mojito",
  "Old Fashioned",
  "Daiquiri",
  "Negroni",
  "Mai Tai",
  "Cosmopolitan",
  "Manhattan",
  "Piña Colada",
  "Whiskey Sour",
  "Gin and Tonic",
  "Bloody Mary",
  "Paloma",
  "Moscow Mule",
  "Tequila Sunrise",
  "Long Island Iced Tea",
  "Caipirinha",
  "Aperol Spritz",
  "Tom Collins",
];
